services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./config:/config:ro
      - ./data:/data
    environment:
      - GATUS_CONFIG_PATH=/config/gatus.yaml
    env_file:
      - .env
    networks:
      - monitor-net

networks:
  monitor-net:
    external: true
