storage:
  type: sqlite
  path: /data/gatus.db

metrics: true

# Combined endpoints from all site configurations
endpoints:
  # INTERNAL INFRASTRUCTURE
  - name: Uptime Kuma (internal)
    group: internal
    url: http://uptime-kuma:3001/
    interval: 30s
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 1500ms"

  - name: Uptime Kuma (public)
    group: external
    url: https://uptime.webifyseo.com/
    interval: 1m
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[CERTIFICATE_EXPIRATION] > 168h"

  - name: Gatus UI (public)
    group: internal
    url: https://monitor.webifyseo.com/
    interval: 1m
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[CERTIFICATE_EXPIRATION] > 168h"

  # CRITICAL INFRASTRUCTURE MONITORING
  - name: Uptime Kuma Critical Monitor
    group: critical-infrastructure  
    url: https://uptime.webifyseo.com/
    interval: 60s
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 3000ms"
    alerts:
      # CRITICAL ALERT: Monitoring infrastructure down for 5+ minutes
      - type: slack
        enabled: true
        failure-threshold: 5  # 5 failures at 60s = 5 minutes
        success-threshold: 1
        send-on-resolved: true
        description: "🚨 CRITICAL: MONITORING INFRASTRUCTURE DOWN - UPTIME KUMA OFFLINE FOR 5+ MINUTES 🚨"
        channel: "critical-alerts"
        url: ${CRITICAL_ALERTS_SLACK}

  - name: Gatus Critical Self-Check
    group: critical-infrastructure
    url: https://monitor.webifyseo.com/
    interval: 60s  
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 3000ms"
    alerts:
      # CRITICAL ALERT: Gatus monitoring down for 5+ minutes  
      - type: slack
        enabled: true
        failure-threshold: 5  # 5 failures at 60s = 5 minutes
        success-threshold: 1
        send-on-resolved: true
        description: "🚨 CRITICAL: GATUS MONITORING SYSTEM DOWN FOR 5+ MINUTES - BLIND TO ALL SITES 🚨"
        channel: "critical-alerts"
        url: ${CRITICAL_ALERTS_SLACK}

  # CLIENT: SLOANE'S BANGKOK
  - name: Sloane BKK Checkout (page OK)
    group: storefront
    url: https://bangkok.sloanes.co.th/checkout/
    interval: 60s
    headers:
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
      Accept-Language: "en-GB,en;q=0.9"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2000ms"
      - "[BODY] == pat(*woocommerce-checkout*)"
      - "[BODY] == pat(*<h1 class=\"page-title\">Checkout</h1>*)"
      - "[BODY] == pat(*<div class=\"woocommerce\"*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "Checkout page monitor failed"
        channel: "client-sloanes"
        url: ${CLIENT1_SLACK}

  - name: Sloane BKK Checkout (no-cache)
    group: storefront
    url: https://bangkok.sloanes.co.th/checkout/
    interval: 180s
    headers:
      Cache-Control: "no-cache"
      Pragma: "no-cache"
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[BODY] == pat(*woocommerce-checkout*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "Checkout (no-cache) failed"
        channel: "client-sloanes"
        url: ${CLIENT1_SLACK}

  - name: Sloane BKK jQuery (static OK)
    group: assets
    url: https://bangkok.sloanes.co.th/wp-includes/js/jquery/jquery.min.js
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1200ms"

  - name: Sloane BKK TLS
    group: certificates
    url: tls://bangkok.sloanes.co.th:443
    interval: 6h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 240h"

  # CLIENT: ESSEX BANNERS
  - name: Essex Banners Heartbeat
    group: health
    url: https://essexbanners.com/wp-includes/js/wp-emoji-release.min.js
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 800ms"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "🚨 ESSEX BANNERS SERVER DOWN - essexbanners.com heartbeat failed"
        channel: "client-essexbanners"
        url: ${CLIENT_ESSEXBANNERS_SLACK}

  - name: Essex Banners Checkout
    group: conversion
    url: https://essexbanners.com/checkout/
    interval: 180s
    headers:
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
      Accept-Language: "en-GB,en;q=0.9"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 3000ms"
      - "[BODY] == pat(*woocommerce-checkout*)"
      - "[BODY] == pat(*checkout*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "🛒 ESSEX BANNERS CHECKOUT BROKEN - essexbanners.com/checkout/ conversion path down"
        channel: "client-essexbanners"
        url: ${CLIENT_ESSEXBANNERS_SLACK}

  - name: Essex Banners Shop Archive
    group: storefront
    url: https://essexbanners.com/product-category/banner-printing/
    interval: 300s
    headers:
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[BODY] == pat(*woocommerce*)"
      - "[BODY] == pat(*product*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "⚠️ ESSEX BANNERS SHOP BROKEN - essexbanners.com product listings down"
        channel: "client-essexbanners"
        url: ${CLIENT_ESSEXBANNERS_SLACK}

  - name: Essex Banners Product Engine
    group: commerce
    url: https://essexbanners.com/product/next-day-pvc-banner-printing/
    interval: 300s
    headers:
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[BODY] == pat(*.add_to_cart_button*)"
      - "[BODY] == pat(*single-product*)"
      - "[BODY] == pat(*woocommerce*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "🛒 ESSEX BANNERS ADD-TO-CART BROKEN - essexbanners.com product engine down"
        channel: "client-essexbanners"
        url: ${CLIENT_ESSEXBANNERS_SLACK}

  - name: Essex Banners TLS
    group: certificates
    url: tls://essexbanners.com:443
    interval: 6h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 240h"
