# Client: Sloane's Bangkok WooCommerce Store
endpoints:
  - name: Sloane BKK Checkout (page OK)
    group: storefront
    url: https://bangkok.sloanes.co.th/checkout/
    interval: 60s
    headers:
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
      Accept-Language: "en-GB,en;q=0.9"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2000ms"
      - "[BODY] == pat(*woocommerce-checkout*)"             # WooCommerce marker
      - "[BODY] == pat(*<h1 class=\"page-title\">Checkout</h1>*)"  # stable title marker
      - "[BODY] == pat(*<div class=\"woocommerce\"*)"       # wrapper div
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "Checkout page monitor failed"
        channel: "client-sloanes"
        url: ${CLIENT1_SLACK}

  - name: Sloane BKK Checkout (no-cache)
    group: storefront
    url: https://bangkok.sloanes.co.th/checkout/
    interval: 180s
    headers:
      Cache-Control: "no-cache"
      Pragma: "no-cache"
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[BODY] == pat(*woocommerce-checkout*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "Checkout (no-cache) failed"
        channel: "client-sloanes"
        url: ${CLIENT1_SLACK}

  - name: Sloane BKK jQuery (static OK)
    group: assets
    url: https://bangkok.sloanes.co.th/wp-includes/js/jquery/jquery.min.js
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1200ms"

  - name: Sloane BKK TLS
    group: certificates
    url: tls://bangkok.sloanes.co.th:443
    interval: 6h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 240h"