# WooCommerce Site Monitoring Template
# Variables to replace:
# Test Shop - Display name for the site (e.g., "New Shop")
# https://testshop.example.com - Full URL without trailing slash (e.g., "https://shop.example.com")
# testshop.example.com - Domain only (e.g., "shop.example.com")
# testshop-example-com - Short name for identification (e.g., "newshop")
# CLIENT_TESTSHOP-EXAMPLE-COM_SLACK - Environment variable name for Slack webhook (e.g., "CLIENT2_SLACK")

endpoints:
  - name: Test Shop Checkout (page OK)
    group: storefront
    url: https://testshop.example.com/checkout/
    interval: 60s
    headers:
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
      Accept-Language: "en-GB,en;q=0.9"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2000ms"
      - "[BODY] == pat(*woocommerce-checkout*)"             # WooCommerce marker
      - "[BODY] == pat(*<h1 class=\"page-title\">Checkout</h1>*)"  # stable title marker
      - "[BODY] == pat(*<div class=\"woocommerce\"*)"       # wrapper div
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "Test Shop checkout page monitor failed"
        channel: "client-testshop-example-com"
        url: $CLIENT_TESTSHOP-EXAMPLE-COM_SLACK

  - name: Test Shop Checkout (no-cache)
    group: storefront
    url: https://testshop.example.com/checkout/
    interval: 180s
    headers:
      Cache-Control: "no-cache"
      Pragma: "no-cache"
      User-Agent: "webifySEO/1.0 (+https://webifyseo.com)"
    conditions:
      - "[STATUS] < 400"
      - "[RESPONSE_TIME] < 2500ms"
      - "[BODY] == pat(*woocommerce-checkout*)"
    alerts:
      - type: slack
        enabled: true
        failure-threshold: 1
        success-threshold: 2
        send-on-resolved: true
        description: "Test Shop checkout (no-cache) failed"
        channel: "client-testshop-example-com"
        url: $CLIENT_TESTSHOP-EXAMPLE-COM_SLACK

  - name: Test Shop jQuery (static OK)
    group: assets
    url: https://testshop.example.com/wp-includes/js/jquery/jquery.min.js
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 1200ms"

  - name: Test Shop TLS
    group: certificates
    url: tls://testshop.example.com:443
    interval: 6h
    conditions:
      - "[CERTIFICATE_EXPIRATION] > 240h"
